### ISSUE TITLE
API listed local IP address

### ISSUE THREAD

**Issue by Daniel74Ger** [team-exor/eiquidus#10]
Hi,

what do I have to change so that the local IP address no longer appears under api, but the test.xyz instead?

**Comment by joeuhren** [comment]
I may need more information, because if I understand correctly you are asking about how to change the host information listed for each API call on the API page? I'm not quite sure if this is what you are asking because there is no setting for this as it pulls the host url directly from the url:
![image](https://user-images.githubusercontent.com/46763106/142786623-759339e2-6e84-405f-a782-b4ac13344156.png)
![image](https://user-images.githubusercontent.com/46763106/142786631-9839ae35-9e00-434f-b4d7-be318b72db9a.png)

**Comment by Daniel74Ger** [comment]
Hi,

Yes, that's what I meant. In the original version it was possible to specify an address.
I must then solve differently.
Thank you very much.

**Comment by joeuhren** [comment]
@Daniel74Ger yes, the original iquidus has a setting to specifically set the host for the API page. We removed that setting in our version since it seemed to be out of place as we couldn't see why you might want to arbitrarily change the API host url from anything other than what you are accessing the site from. If you feel there is a good use case for bringing this feature back, please let me know and we can discuss re-adding it.

**Comment by Daniel74Ger** [comment]
all good. i fixed it through the firewall. now it is as requested.

thank you for your quick help.
