### ISSUE TITLE
Altmarkets No data to display

### ISSUE THREAD

**Issue by skyrawrcode** [team-exor/eiquidus#2]
AltMarkets Error!
This market has no data to display. 

The sync succeeds and the database does appear to have the data.

trying to add pairs 

```
 "altmarkets": {
        // enabled: Enable/disable the altmarkets exchange (true/false)
        //          If set to false, the altmarkets page will be completely inaccessible and no market data will be downloaded for this exchange
        "enabled": true,
        // trading_pairs: An array of market trading pair symbols
        //                You can add as many trading pairs as necessary
        //                All entries must specify your coins symbol as it is displayed on the exchange, followed by a slash (/) and ending with the symbol of the market or asset that is being traded against
        //                Ex: "LTC/BTC", "LTC/USDT", "LTC/ETH"
        "trading_pairs": [ "LDOGE/DOGE",  "LDOGE/LTC", "LDOGE/ETH" ]
      }
```

**Comment by skyrawrcode** [comment]
Yeah i see why this doesn't work now. I need to grab the changes from the holy roger.

**Comment by joeuhren** [comment]
Thanks for bringing this to my attention. It's almost bed time for me today but I'll roll out a proper fix soon.

**Comment by joeuhren** [comment]
OK, I added support for the altmarkets v2 api as well as some small fixes/improvements to the markets page in general. I believe this should get you fixed up so do a `git pull` and give it a shot.

I also want to mention that it seems 2 of the 3 pairs you mentioned are only available on the old v1 altmarkets site. The new LDOGE pairs seem to be LDOGE/BTC, LDOGE/CRO and LDOGE/ETH. Since trading is disabled on the old site, you'll only have access to the new pairs from now on.

Please let me know if you notice any problems with the altmarkets fix, as it could be possible that I overlooked something. I'll keep the issue open and close it in a few days if I don't hear any further complaints.

**Comment by skyrawrcode** [comment]
Works like a charm.
