### ISSUE TITLE
the list of masternodes,  lists a maximum of 4388 masternodes

### ISSUE THREAD

**Issue by luc1anocruz** [team-exor/eiquidus#30]
the list of masternodes, both in the api and in the masternode tab, lists a maximum of 4388 masternodes, and the currency has more than 6 thousand masternodes, I looked in the settings for there was some limit but I did not find anything about it
[https://i.imgur.com/SxZixOo.png](https://i.imgur.com/SxZixOo.png)

**Comment by joeuhren** [comment]
There shouldn't be any limitations in the explorer for masternodes. It just saves whatever the wallet is returning.

Have you changed the api_cmds > getmasternodelist option at all or is it still running the default `listmasternodes` cmd? Can you confirm that there isn't some type of limitation in the wallet daemon that is only returning a subset of the results when you run that cmd manually from the wallet itself? My guess is that you are maybe only returning the list of enabled masternodes and might need to change the cmd or pass another paramter to return all masternodes.

**Comment by luc1anocruz** [comment]
> There shouldn't be any limitations in the explorer for masternodes. It just saves whatever the wallet is returning.
> 
> Have you changed the api_cmds > getmasternodelist option at all or is it still running the default `listmasternodes` cmd? Can you confirm that there isn't some type of limitation in the wallet daemon that is only returning a subset of the results when you run that cmd manually from the wallet itself? My guess is that you are maybe only returning the list of enabled masternodes and might need to change the cmd or pass another paramter to return all masternodes.

in the wallet cmd it lists all normally, returning ENABLE, ACTIVE and EXPIRED, in the website it lists randomly, a little ENABLE, ACTIVE AND EXPIRED

**Comment by joeuhren** [comment]
which coin is this for?

**Comment by luc1anocruz** [comment]
my cmd is  kicksoccer-cli listmasternodes   KSOC Sports 
I tried changing the getmasternodelist command in the settings to listmasternodes but it gives an error

Unknown setting 'api_page.public_apis.ext.listmasternodes' has been ignored. This setting doesn't exist or was removed.
setting 'api_page.public_apis.ext.getmasternodelist' is missing. Loading default value.

**Comment by luc1anocruz** [comment]
I think it's a limitation of the explorer, because if it were the cmd, it wouldn't list any, and it's listing both ENABLE and ACTIVE or EXPIRED, only with a maximum limit of 4388.
[https://i.imgur.com/o8ULcL9.png](https://i.imgur.com/o8ULcL9.png)

**Comment by joeuhren** [comment]
You're right, it was a problem with the explorer in this case. The issue was that there are certain transactions in the KOSC Sports blockchain where there are hundreds of masternodes created off the same txid and the explorer was expecting each masternode to have a unique txid. This was causing all the other MNs with the same txid to update the 1st record instead of adding a new record.

I've released a small fix to correct this shortcoming. Either run the built-in updater with `npm run update-explorer` or else you can manually merge the update from here: https://github.com/team-exor/eiquidus/commit/e5bd30a457ff0121fc036fdf3cb960d431ef55a5

Update your explorer code and try syncing masternodes again. Let me know how it goes.

**Comment by luc1anocruz** [comment]
Perfect! update tested and approved, now loads all masternodes, thanks for the great job to this excellent explorer.
